import type { DecisionBlock, LongFormEnding } from '../long-form-tree';
import { createLongFormTree } from '../long-form-tree';

/**
 * Commodity Shock — Republic of Kemet (20 decisions)
 */
const blocks: DecisionBlock[] = [
  {
    phase: 1,
    title: 'Commodity Shock & Development Squeeze',
    narrative: `You lead the Republic of Kemet. Some trade economists argue that unequal exchange — the terms on which you export commodities — explains why exports do not generate the wealth you might expect; value flows toward the centre. Scholars of development suggest the "resource curse" is not accidental but designed — extraction structured to benefit outsiders. Advocates of food sovereignty argue that feeding your people must come first. What do you do first?`,
    choices: [
      { id: 'fx', text: 'Intervene in currency', consequence: '', effects: { priceStability: 10, externalBalance: -15, debtBurden: 5 } },
      { id: 'subsidies', text: 'Subsidize food and fuel', consequence: '', effects: { publicSupport: 12, debtBurden: 15, priceStability: 5 } },
      { id: 'diversify', text: 'Accelerate diversification', consequence: '', effects: { economicStrength: 5, externalBalance: 8, publicSupport: -8 } },
    ],
  },
  { phase: 1, title: 'Reserves', narrative: `Reserves are falling. Without them, you cannot defend the currency or pay for imports. Do you seek an IMF swap line — emergency liquidity in exchange for conditions — or impose capital controls to stem outflows and keep what you have? The swap may ease the crunch but comes with strings; controls assert sovereignty but may spook investors.`, choices: [{ id: 'imf', text: 'Seek IMF swap', consequence: '', effects: { externalBalance: 5, sovereignty: -10 } }, { id: 'controls', text: 'Impose capital controls', consequence: '', effects: { sovereignty: 8, externalBalance: 5 } }] },
  { phase: 1, title: 'Food Imports', narrative: `Advocates of food sovereignty argue that no country can develop while depending on imported food — it drains foreign exchange and leaves you vulnerable to global price spikes. Do you subsidise food imports to keep people fed in the short term, or invest in domestic production to build self-sufficiency? Subsidies are faster but costly; domestic investment takes time but builds resilience.`, choices: [{ id: 'subsidize', text: 'Subsidize imports', consequence: '', effects: { publicSupport: 10, debtBurden: 10 } }, { id: 'domestic', text: 'Invest in domestic production', consequence: '', effects: { sovereignty: 10, economicStrength: 8 } }] },
  { phase: 1, title: 'Export Taxes', narrative: `Commodity exports often leave most of the value abroad — raw materials sold cheap, processed elsewhere. Do you tax exports to capture more of that value for the treasury and fund development? It may reduce the incentive to export or provoke pushback from mining and trading firms.`, choices: [{ id: 'yes', text: 'Tax exports', consequence: '', effects: { sovereignty: 8, economicStrength: 3 } }, { id: 'no', text: 'No', consequence: '', effects: { economicStrength: 5 } }] },
  { phase: 2, title: 'Terms of Trade', narrative: `Theory suggests that terms of trade — the ratio of export to import prices — are often stacked against commodity exporters. Do you seek regional trade blocs to negotiate from strength and improve those terms, or go it alone? Blocs could give you leverage; going alone may be simpler but weaker.`, choices: [{ id: 'yes', text: 'Seek regional blocs', consequence: '', effects: { sovereignty: 8, externalBalance: 5 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 2, title: 'Diversification', narrative: `Commodity dependence leaves you at the mercy of world prices. Do you invest in manufacturing — processing raw materials at home, building new industries — or stay commodity-focused and ride the cycles? Manufacturing could add value and jobs but requires capital and time; staying focused may be simpler but keeps you vulnerable.`, choices: [{ id: 'manufacturing', text: 'Invest in manufacturing', consequence: '', effects: { economicStrength: 10, debtBurden: 8 } }, { id: 'commodity', text: 'Stay commodity-focused', consequence: '', effects: { economicStrength: 5 } }] },
  { phase: 2, title: 'Currency', narrative: `A weaker currency makes exports cheaper and imports dearer — it could boost competitiveness but also fuel inflation. Do you devalue to support exporters, or defend the rate to protect purchasing power and stability? Devaluation may help the trade balance but hurt households; defending may please markets but strain reserves.`, choices: [{ id: 'devalue', text: 'Devalue', consequence: '', effects: { economicStrength: 10, priceStability: -10 } }, { id: 'defend', text: 'Defend', consequence: '', effects: { priceStability: 8, externalBalance: -10 } }] },
  { phase: 2, title: 'Subsidy Bill', narrative: `Subsidies for food and fuel are costly — they strain the budget and can distort markets. Do you target them to the poorest, cutting costs but risking political backlash, or broaden them to maintain support? Targeting is fiscally responsible; broadening may keep people calm but add to debt.`, choices: [{ id: 'target', text: 'Target subsidies', consequence: '', effects: { debtBurden: -5, publicSupport: -3 } }, { id: 'broaden', text: 'Broaden', consequence: '', effects: { publicSupport: 10, debtBurden: 10 } }] },
  { phase: 3, title: 'Resource Extraction', narrative: `Scholars of development argue that resource wealth often flows out by design — contracts, transfer pricing, and ownership structures that favour foreign firms. Do you impose profit-sharing or stricter terms on extractive industries to keep more value at home? It could increase revenue but may deter investment or provoke conflict.`, choices: [{ id: 'yes', text: 'Impose profit-sharing', consequence: '', effects: { sovereignty: 12, economicStrength: 5 } }, { id: 'no', text: 'No', consequence: '', effects: { economicStrength: 8 } }] },
  { phase: 3, title: 'Import Substitution', narrative: `Import substitution — producing at home what you used to import — can build industry and save foreign exchange. It can also mean protecting inefficient firms. Do you push substitution for key goods — fertiliser, machinery, basic manufactures — or rely on imports? Substitution builds capacity but takes time; imports are faster but keep you dependent.`, choices: [{ id: 'yes', text: 'Push substitution', consequence: '', effects: { sovereignty: 10, economicStrength: 8 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 3, title: 'Debt', narrative: `Debt service is rising — a growing share of revenue goes to creditors. Do you seek restructuring — negotiating lower payments, longer terms, or partial relief — or pay in full to protect your credit standing? Restructuring may ease the burden but could damage relations with lenders.`, choices: [{ id: 'yes', text: 'Seek restructuring', consequence: '', effects: { debtBurden: -15, sovereignty: 5 } }, { id: 'no', text: 'Pay in full', consequence: '', effects: { debtBurden: -5 } }] },
  { phase: 3, title: 'Regional Cooperation', narrative: `Dollar-dominated payment systems can be weaponised — sanctions, surveillance, exclusion. Do you build South-South payment systems and regional alternatives to reduce dependence on Northern financial infrastructure? It could expand your options but requires coordination and may face resistance.`, choices: [{ id: 'yes', text: 'Build alternatives', consequence: '', effects: { sovereignty: 12 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 4, title: 'Mid-Term', narrative: `Diversification is underway — some new industries are taking root. Do you accelerate, pouring more resources into the transition, or consolidate, locking in gains and managing debt? Acceleration may deepen the shift but add to strain; consolidation may be safer but slower.`, choices: [{ id: 'accelerate', text: 'Accelerate', consequence: '', effects: { economicStrength: 12, debtBurden: 8 } }, { id: 'consolidate', text: 'Consolidate', consequence: '', effects: { debtBurden: -8 } }] },
  { phase: 4, title: 'Commodity Revenue', narrative: `Commodity prices have recovered — a windfall. Do you save it in a stabilisation fund for the next downturn, or spend it on development — infrastructure, industry, social programs? Saving builds resilience; spending may accelerate growth but leaves you exposed when prices fall again.`, choices: [{ id: 'save', text: 'Save', consequence: '', effects: { externalBalance: 15, debtBurden: -10 } }, { id: 'spend', text: 'Spend on development', consequence: '', effects: { economicStrength: 12, publicSupport: 10 } }] },
  { phase: 4, title: 'Food Sovereignty', narrative: `Do you prioritise food self-sufficiency — investing in agriculture so you can feed your people without depending on imports? It would reduce vulnerability to global price spikes and save foreign exchange, but it takes land, water, and time.`, choices: [{ id: 'yes', text: 'Prioritize', consequence: '', effects: { sovereignty: 10, publicSupport: 10 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 4, title: 'Value Addition', narrative: `Exporting raw commodities often captures less value than processing them first. Do you require local processing — refining, smelting, manufacturing — before export? It could create jobs and capture more value, but may require investment and could face resistance from buyers who prefer to process elsewhere.`, choices: [{ id: 'yes', text: 'Require processing', consequence: '', effects: { economicStrength: 10, sovereignty: 8 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 5, title: 'Year Two', narrative: `Progress is visible — diversification is advancing, some reforms have taken hold. Do you deepen reforms, pushing further, or ease off to consolidate and avoid overreach? Deepening may achieve more but could strain capacity; easing may stabilise but slow momentum.`, choices: [{ id: 'deepen', text: 'Deepen', consequence: '', effects: { sovereignty: 10 } }, { id: 'ease', text: 'Ease', consequence: '', effects: { economicStrength: 5 } }] },
  { phase: 5, title: 'IMF Relations', narrative: `The IMF has offered a program — financing in exchange for policy conditions. Do you engage and accept the terms, or stay independent and finance development on your own? Engagement may ease debt and unlock other financing but constrains policy; independence preserves sovereignty but may mean tighter budgets.`, choices: [{ id: 'engage', text: 'Engage', consequence: '', effects: { debtBurden: -10, sovereignty: -10 } }, { id: 'independent', text: 'Stay independent', consequence: '', effects: { sovereignty: 10 } }] },
  { phase: 5, title: 'Legacy', narrative: `What model do you leave for Kemet? Sovereign commodity management — controlling resources, capturing value, reducing dependence? Or a diversified economy — less tied to any single commodity, more resilient to shocks?`, choices: [{ id: 'sovereign', text: 'Sovereign commodity management', consequence: '', effects: { sovereignty: 12 } }, { id: 'diversified', text: 'Diversified economy', consequence: '', effects: { economicStrength: 10 } }] },
  { phase: 5, title: 'Final Decision', narrative: `Your last decision for Kemet. The path you choose will shape how your successors govern — and whether the commodity trap is finally broken.`, choices: [{ id: 'sovereign', text: 'Sovereign path', consequence: '', effects: { sovereignty: 10, economicStrength: 5 } }, { id: 'diversified', text: 'Diversified path', consequence: '', effects: { economicStrength: 10 } }, { id: 'mixed', text: 'Mixed path', consequence: '', effects: { economicStrength: 6, sovereignty: 6 } }] },
];

const endings: LongFormEnding[] = [
  { id: 'victory', endingType: 'victory', title: 'Breaking the Commodity Trap', endingNarrative: `You diversified and built sovereignty. Kemet is less dependent on volatile world markets.` },
  { id: 'partial', endingType: 'partial_victory', title: 'Partial Success', endingNarrative: `You made progress. Some dependence remains. The transition continues.` },
  { id: 'defeat', endingType: 'defeat', title: 'Commodity Trap', endingNarrative: `The trap holds. Volatility and dependence persist. The struggle continues.` },
];

const { getNode } = createLongFormTree(blocks, endings, (i) => (i === 0 ? 0 : i === 1 ? 1 : 2));
export { getNode };
