import type { DecisionBlock, LongFormEnding } from '../long-form-tree';
import { createLongFormTree } from '../long-form-tree';

/**
 * Independence & Underdevelopment — Republic of Uhuru (20 decisions)
 */
const blocks: DecisionBlock[] = [
  {
    phase: 1,
    title: 'Independence & Underdevelopment',
    narrative: `Your country, the Republic of Uhuru, has just won independence. Development economists argue that peripheral countries must "delink" from global markets to develop on their own terms. Trade theory suggests that free trade can transfer value toward the core. Some scholarship describes "super-exploitation" — wages held below the cost of reproducing labour. Advocates of food sovereignty argue that no country develops without feeding itself first. What do you do first?`,
    choices: [
      { id: 'state', text: 'State-led industrialisation', consequence: '', effects: { economicStrength: 12, sovereignty: 10, debtBurden: 15 }, nextBlock: 20 },
      { id: 'mixed', text: 'Mixed economy', consequence: '', effects: { economicStrength: 8, publicSupport: 8, debtBurden: 8 } },
      { id: 'market', text: 'Market-led growth', consequence: '', effects: { economicStrength: 10, sovereignty: -10, publicSupport: -5 }, nextBlock: 21 },
    ],
  },
  { phase: 1, title: 'Land Reform', narrative: `Scholars of agrarian development emphasize land — who owns it, who works it, who eats from it. Colonial patterns left land concentrated in few hands. Do you launch agrarian reform to redistribute land and build a domestic food base, or defer and focus on industry first? Reform could secure rural support but may unsettle elites.`, choices: [{ id: 'yes', text: 'Launch land reform', consequence: '', effects: { sovereignty: 10, publicSupport: 12, economicStrength: 5 } }, { id: 'no', text: 'Defer', consequence: '', effects: { economicStrength: 3 } }] },
  { phase: 1, title: 'Trade Policy', narrative: `Some trade economists argue that unequal exchange — trading on terms that favour the core — transfers value northward. Do you raise tariffs to protect infant industry and keep more value at home, or stay open and hope that integration brings investment and growth? Protection may nurture industry but risks retaliation; openness may bring capital but also dependence.`, choices: [{ id: 'yes', text: 'Raise tariffs', consequence: '', effects: { sovereignty: 8, economicStrength: 5 } }, { id: 'no', text: 'Stay open', consequence: '', effects: { economicStrength: 8, sovereignty: -8 } }] },
  { phase: 1, title: 'Foreign Investment', narrative: `Foreign capital could bring technology, jobs, and foreign exchange — but it could also extract profits, dictate terms, and tie your economy to external interests. Do you welcome it with open arms, or restrict it to protect sovereignty and steer development? Welcome it and growth may come faster; restrict it and you keep more control.`, choices: [{ id: 'welcome', text: 'Welcome it', consequence: '', effects: { economicStrength: 12, sovereignty: -12 } }, { id: 'restrict', text: 'Restrict it', consequence: '', effects: { sovereignty: 12, economicStrength: 2 } }] },
  { phase: 2, title: 'Food Sovereignty', narrative: `Advocates of food sovereignty argue that no country develops without feeding itself first. Importing food drains foreign exchange and leaves you vulnerable. Do you make a major agricultural investment — irrigation, seeds, storage — or keep investment modest and prioritise industry? Agriculture takes time to pay off but builds resilience.`, choices: [{ id: 'major', text: 'Major agricultural investment', consequence: '', effects: { economicStrength: 8, sovereignty: 10, publicSupport: 10 } }, { id: 'modest', text: 'Modest investment', consequence: '', effects: { economicStrength: 4 } }] },
  { phase: 2, title: 'Wages', narrative: `Dependency theorists argue that keeping wages low boosts exports but destroys domestic demand — workers cannot buy what they make. Do you raise minimum wages to build a domestic market and improve living standards, or keep wages low to attract investment and stay competitive? Higher wages may reduce exports but expand the home market.`, choices: [{ id: 'yes', text: 'Raise minimum wages', consequence: '', effects: { publicSupport: 15, economicStrength: 5 } }, { id: 'no', text: 'Keep wages low', consequence: '', effects: { economicStrength: 10, publicSupport: -10 } }] },
  { phase: 2, title: 'IMF Approach', narrative: `The IMF has offered a program. Research on structural adjustment shows that conditionality often dismantles state capacity — cutting spending, privatising, opening markets — in ways that can undermine development. Do you engage and accept the conditions, or refuse and seek other financing? Engagement may ease debt but at a cost to policy space.`, choices: [{ id: 'engage', text: 'Engage with IMF', consequence: '', effects: { debtBurden: -10, sovereignty: -15 } }, { id: 'refuse', text: 'Refuse', consequence: '', effects: { sovereignty: 15, debtBurden: 5 } }] },
  { phase: 2, title: 'State Enterprises', narrative: `State-owned enterprises can lead development in sectors the private sector will not touch — heavy industry, infrastructure, strategic goods. They can also become inefficient, politicised, or both. Do you expand SOEs to drive industrialisation, or rely on the private sector to fill the gap? Expansion builds state capacity but adds to debt; reliance on the private sector may be faster but less controllable.`, choices: [{ id: 'expand', text: 'Expand SOEs', consequence: '', effects: { economicStrength: 10, sovereignty: 12, debtBurden: 8 } }, { id: 'private', text: 'Rely on private sector', consequence: '', effects: { economicStrength: 8, sovereignty: -5 } }] },
  { phase: 3, title: 'Delinking', narrative: `Development economists argue that peripheral countries should "delink" — subordinate external relations to internal development, rather than tailoring policy to please foreign investors and creditors. Do you pursue delinking, prioritising domestic industry and food security over integration, or stay integrated and accept the constraints that come with it?`, choices: [{ id: 'yes', text: 'Pursue delinking', consequence: '', effects: { sovereignty: 15, economicStrength: 3 } }, { id: 'no', text: 'Stay integrated', consequence: '', effects: { economicStrength: 10, sovereignty: -10 } }] },
  { phase: 3, title: 'Education', narrative: `Education builds human capital — the skills and knowledge that development requires. Colonial systems often left literacy and technical training neglected. Do you make a major education push — schools, teacher training, vocational programs — or keep increases modest? Heavy investment pays off over decades; modest steps cost less but may not be enough.`, choices: [{ id: 'yes', text: 'Major education push', consequence: '', effects: { humanDevelopment: 15, debtBurden: 8 } }, { id: 'modest', text: 'Modest increase', consequence: '', effects: { humanDevelopment: 5 } }] },
  { phase: 3, title: 'Resource Nationalization', narrative: `Key resources — minerals, oil, land — are often controlled by foreign firms or a narrow elite. Nationalising them could capture rents for development and assert sovereignty, but it may trigger capital flight, sanctions, or conflict. Do you nationalise, or leave ownership as it is? Nationalisation sends a signal; the status quo may be safer but leaves value abroad.`, choices: [{ id: 'yes', text: 'Nationalize', consequence: '', effects: { sovereignty: 15, economicStrength: 8, internationalStanding: -10 } }, { id: 'no', text: 'No', consequence: '', effects: { economicStrength: 5 } }] },
  { phase: 3, title: 'South-South Cooperation', narrative: `Trade with other developing countries could reduce dependence on the North — building regional markets, sharing technology, and negotiating from strength. It could also mean trading with partners who have less to offer in the short term. Do you prioritise South-South trade and cooperation, or focus on the North where markets are larger and capital flows?`, choices: [{ id: 'yes', text: 'Prioritize South-South', consequence: '', effects: { sovereignty: 10, economicStrength: 5 } }, { id: 'no', text: 'Focus on North', consequence: '', effects: { economicStrength: 8, sovereignty: -8 } }] },
  { phase: 4, title: 'Mid-Term', narrative: `Industry is growing but unevenly — some sectors thrive, others lag. Do you double down on what is working, concentrating resources in the strongest areas, or diversify to spread risk and build a broader base? Doubling down may accelerate growth in a few sectors; diversifying may be slower but more resilient.`, choices: [{ id: 'double', text: 'Double down', consequence: '', effects: { economicStrength: 12 } }, { id: 'diversify', text: 'Diversify', consequence: '', effects: { economicStrength: 8, sovereignty: 5 } }] },
  { phase: 4, title: 'Comprador Elite', narrative: `A local elite whose interests are tied to foreign capital — imports, finance, raw material exports — is resisting your development agenda. Some analysts describe such groups as "comprador" — serving external masters rather than national development. Do you confront them and push through reforms, or accommodate them to keep the peace?`, choices: [{ id: 'yes', text: 'Confront', consequence: '', effects: { sovereignty: 12, publicSupport: 10 } }, { id: 'no', text: 'Accommodate', consequence: '', effects: { economicStrength: 5 } }] },
  { phase: 4, title: 'Debt Service', narrative: `Debt service is rising — a growing share of revenue goes to creditors. Do you seek restructuring — negotiating lower payments, longer terms, or debt relief — or pay in full to protect your credit standing? Restructuring may ease the burden but could damage relations with lenders; paying in full preserves standing but may starve development.`, choices: [{ id: 'restructure', text: 'Seek restructuring', consequence: '', effects: { debtBurden: -15, internationalStanding: -8 } }, { id: 'pay', text: 'Pay in full', consequence: '', effects: { debtBurden: -5, internationalStanding: 5 } }] },
  { phase: 4, title: 'Industrial Policy', narrative: `Do you target specific industries — picking winners, subsidising strategic sectors, protecting infant firms — or let the market decide which industries emerge? Industrial policy has worked in some late developers but failed in others; market-led growth can be faster but may lock you into low-value activities.`, choices: [{ id: 'target', text: 'Target industries', consequence: '', effects: { economicStrength: 12, sovereignty: 8 } }, { id: 'market', text: 'Let market decide', consequence: '', effects: { economicStrength: 6 } }] },
  { phase: 5, title: 'Year Two', narrative: `Progress is visible — industry is growing, some reforms have taken hold. Do you accelerate, pushing harder and faster, or consolidate, locking in gains and managing risks? Acceleration may achieve more but could overstretch; consolidation may be safer but slower.`, choices: [{ id: 'accelerate', text: 'Accelerate', consequence: '', effects: { economicStrength: 10, debtBurden: 8 } }, { id: 'consolidate', text: 'Consolidate', consequence: '', effects: { debtBurden: -8 } }] },
  { phase: 5, title: 'Multilateral Institutions', narrative: `Regional development banks offer an alternative to the IMF — financing with different conditions, sometimes more aligned with Southern interests. Do you join and use them as a counterweight to Northern institutions, or stay out? Joining could expand your options; staying out may keep you freer but with fewer resources.`, choices: [{ id: 'yes', text: 'Join regional banks', consequence: '', effects: { sovereignty: 10 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 5, title: 'Legacy', narrative: `What development model do you leave? Sovereign development — state-led, delinked, building domestic capacity on your own terms? Or integrated development — open to trade and capital, growing through connection to global markets?`, choices: [{ id: 'sovereign', text: 'Sovereign development', consequence: '', effects: { sovereignty: 15 } }, { id: 'integrated', text: 'Integrated development', consequence: '', effects: { economicStrength: 10 } }] },
  { phase: 5, title: 'Final Decision', narrative: `Your last decision for Uhuru. The path you choose now will shape how your successors govern — and how history judges your independence.`, choices: [{ id: 'state', text: 'State-led legacy', consequence: '', effects: { sovereignty: 10, economicStrength: 8 } }, { id: 'mixed', text: 'Mixed legacy', consequence: '', effects: { economicStrength: 8, publicSupport: 8 } }, { id: 'market', text: 'Market legacy', consequence: '', effects: { economicStrength: 10, sovereignty: -10 } }] },
  { phase: 1, title: 'Planning the Commanding Heights', narrative: `You have chosen state-led industrialisation. The question is which sectors to prioritise. Do you focus on heavy industry — steel, machinery, chemicals — or on light industry and consumer goods first? Heavy industry builds the base but takes longer; light industry may create jobs faster.`, choices: [{ id: 'heavy', text: 'Heavy industry first', consequence: '', effects: { economicStrength: 10, sovereignty: 10, debtBurden: 10 }, nextBlock: 1 }, { id: 'light', text: 'Light industry first', consequence: '', effects: { economicStrength: 8, publicSupport: 5, debtBurden: 5 }, nextBlock: 1 }] },
  { phase: 1, title: 'Opening to Capital', narrative: `You have chosen market-led growth. The question is how fast to open. Do you liberalise quickly — removing tariffs, welcoming foreign investment, floating the currency — or gradually, protecting some sectors while opening others? Quick opening may attract capital but risks shock; gradual opening may be safer but slower.`, choices: [{ id: 'quick', text: 'Liberalise quickly', consequence: '', effects: { economicStrength: 12, sovereignty: -15 }, nextBlock: 1 }, { id: 'gradual', text: 'Open gradually', consequence: '', effects: { economicStrength: 8, sovereignty: -5 }, nextBlock: 1 }] },
];

const endings: LongFormEnding[] = [
  { id: 'victory', endingType: 'victory', title: 'Sovereign Development', endingNarrative: `You built industry through state action and delinking. Uhuru is on a sovereign path.` },
  { id: 'partial', endingType: 'partial_victory', title: 'Mixed Development', endingNarrative: `You found a balance between state and market. Progress is real but uneven.` },
  { id: 'defeat', endingType: 'defeat', title: 'Dependent Development', endingNarrative: `Growth came but sovereignty was traded. The struggle for genuine development continues.` },
];

const { getNode } = createLongFormTree(blocks, endings, (i) => (i === 0 ? 0 : i === 1 ? 1 : 2));
export { getNode };
