import type { DecisionBlock, LongFormEnding } from '../long-form-tree';
import { createLongFormTree } from '../long-form-tree';

/**
 * Rising Industrializer — People's Republic of Donghai (20 decisions)
 */
const blocks: DecisionBlock[] = [
  {
    phase: 1,
    title: 'Rising Industrializer',
    narrative: `You lead the People's Republic of Donghai. Dependency theorists argue that development can be "dependent" — growth that serves foreign capital rather than building sovereign capacity. Development economists warn that opening without domestic capacity can cause deindustrialisation. Historical analysis suggests that monopoly capital seeks super-profits abroad. Scholars of geopolitical economy argue that states shape outcomes and that a multipolar world offers alternatives. What do you do first?`,
    choices: [
      { id: 'full', text: 'Full speed ahead', consequence: 'Investment surges; growth accelerates but inflation and debt rise.', effects: { economicStrength: 15, priceStability: -10, debtBurden: 10 }, nextBlock: 20 },
      { id: 'managed', text: 'Managed growth', consequence: 'Steady expansion with fewer imbalances.', effects: { economicStrength: 8, priceStability: 5, publicSupport: 5 } },
      { id: 'shared', text: 'Shared gains', consequence: 'Workers and households see more of the benefits of growth.', effects: { publicSupport: 15, economicStrength: 5, debtBurden: 5 }, nextBlock: 21 },
    ],
  },
  { phase: 1, title: 'State vs Market', narrative: `Do you expand state-directed investment — the government picking sectors, funding projects, steering development — or rely on private capital to drive growth? State direction can target strategic goals but may be inefficient; private capital may be more dynamic but less controllable.`, choices: [{ id: 'state', text: 'Expand state investment', consequence: 'Strategic sectors receive targeted funding and direction.', effects: { economicStrength: 12, sovereignty: 10 } }, { id: 'private', text: 'Rely on private', consequence: 'Private capital drives growth but with less state control.', effects: { economicStrength: 10, sovereignty: -5 } }, { id: 'mixed', text: 'Public-private ventures in strategic sectors', consequence: 'Joint ventures share risk and align state goals with private capital.', effects: { economicStrength: 11, sovereignty: 5 } }] },
  { phase: 1, title: 'Wages', narrative: `Dependency theorists argue that keeping wages low boosts exports but destroys domestic demand — workers cannot buy what they make. Do you raise wages to build a home market and share gains, or keep them low to stay competitive? Higher wages may reduce export margins but expand domestic consumption.`, choices: [{ id: 'yes', text: 'Raise wages', consequence: 'Domestic demand grows as workers can afford more.', effects: { publicSupport: 15, economicStrength: 5 } }, { id: 'no', text: 'Keep low', consequence: 'Exports stay competitive but the home market remains weak.', effects: { economicStrength: 12, publicSupport: -8 } }, { id: 'sectoral', text: 'Raise wages only in non-export sectors', consequence: 'You boost domestic demand in services and construction while keeping export industries competitive.', effects: { publicSupport: 8, economicStrength: 9 } }] },
  { phase: 1, title: 'Foreign Investment', narrative: `Foreign direct investment can bring technology, jobs, and capital — but it can also extract profits and tie your economy to external interests. Some argue that capital seeks super-profits abroad. Do you restrict FDI to protect sovereignty and steer development, or welcome it to accelerate growth?`, choices: [{ id: 'restrict', text: 'Restrict FDI', consequence: 'Domestic firms gain space but growth slows.', effects: { sovereignty: 12, economicStrength: 2 } }, { id: 'welcome', text: 'Welcome FDI', consequence: 'Foreign capital floods in; growth surges but dependence deepens.', effects: { economicStrength: 15, sovereignty: -10 } }, { id: 'conditional', text: 'Welcome FDI with local-content and joint-venture rules', consequence: 'Investment flows in but local partners and spillovers are required.', effects: { economicStrength: 10, sovereignty: 3 } }] },
  { phase: 2, title: 'Export Strategy', narrative: `Export-led growth can earn foreign exchange and discipline firms to compete globally — but it may neglect the home market. Do you prioritise export discipline, pushing firms to sell abroad, or domestic demand, building a market at home? Exports bring in revenue; domestic demand may be more stable and inclusive.`, choices: [{ id: 'export', text: 'Export discipline', consequence: 'Firms compete globally; foreign exchange flows in.', effects: { economicStrength: 12 } }, { id: 'domestic', text: 'Domestic demand', consequence: 'A stronger home market makes growth more inclusive.', effects: { publicSupport: 12, economicStrength: 8 } }, { id: 'balanced', text: 'Export first, reinvest in domestic capacity', consequence: 'You earn foreign exchange now and channel it into building the home market.', effects: { economicStrength: 10, publicSupport: 6 } }] },
  { phase: 2, title: 'Inflation', narrative: `Inflation is rising. Do you impose price controls to protect households and anchor expectations, or raise interest rates to cool demand? Price controls may ease the pain but can cause shortages; rate hikes may tame inflation but slow growth and employment.`, choices: [{ id: 'controls', text: 'Price controls', consequence: 'Households are protected but shortages may emerge.', effects: { priceStability: 10, publicSupport: 8 } }, { id: 'rates', text: 'Raise rates', consequence: 'Inflation cools but growth and jobs slow.', effects: { priceStability: 8, economicStrength: -5 } }, { id: 'targeted', text: 'Control prices on essentials, tighten credit moderately', consequence: 'You shield food and fuel while gently cooling credit-fuelled demand.', effects: { priceStability: 9, publicSupport: 6, economicStrength: -2 } }] },
  { phase: 2, title: 'South-South', narrative: `Scholars of multipolarity argue that a shifting global order offers alternatives to dependence on Northern markets. Do you prioritise South-South trade — building ties with other developing countries — or focus on the North where markets are larger? South-South could reduce dependence; the North may offer more immediate gains.`, choices: [{ id: 'yes', text: 'Prioritize', consequence: 'New Southern partners reduce dependence on Northern markets.', effects: { sovereignty: 10, economicStrength: 5 } }, { id: 'no', text: 'Focus on North', consequence: 'Larger markets bring faster gains but deeper dependence.', effects: { economicStrength: 10, sovereignty: -5 } }, { id: 'parallel', text: 'Pursue both — North for revenue, South for diversification', consequence: 'You keep Northern markets while building Southern ties as a hedge.', effects: { economicStrength: 8, sovereignty: 3 } }] },
  { phase: 2, title: 'Rural Development', narrative: `Industry is concentrated in cities; rural areas lag behind. Do you invest in rural areas — agriculture, infrastructure, services — to share the gains of development, or focus on industry and let the countryside wait? Rural investment may slow headline growth but spread benefits; industry-first may accelerate GDP but deepen inequality.`, choices: [{ id: 'yes', text: 'Invest in rural', consequence: 'The countryside shares in development; inequality narrows.', effects: { publicSupport: 15, economicStrength: 6 } }, { id: 'no', text: 'Focus on industry', consequence: 'Headline growth accelerates but regional gaps widen.', effects: { economicStrength: 12 } }, { id: 'agro', text: 'Agro-industry: link rural output to urban factories', consequence: 'You invest in processing and supply chains that connect farm and factory.', effects: { publicSupport: 10, economicStrength: 9 } }] },
  { phase: 3, title: 'Subimperialism', narrative: `As you industrialise, you could extract raw materials and labour from smaller neighbours — replicating the patterns that constrained your own development. Some scholarship describes such behaviour as "subimperial." Do you avoid exploiting neighbours, building more equitable regional ties, or pursue advantage where you can?`, choices: [{ id: 'yes', text: 'Avoid exploitation', consequence: 'Regional ties are built on more equitable terms.', effects: { sovereignty: 8, publicSupport: 5 } }, { id: 'no', text: 'Pursue advantage', consequence: 'You extract gains from neighbours; growth rises but reputation suffers.', effects: { economicStrength: 10 } }, { id: 'reciprocal', text: 'Seek reciprocal regional integration', consequence: 'You propose win-win trade and investment, but implementation is uneven.', effects: { economicStrength: 6, sovereignty: 5, publicSupport: 3 } }] },
  { phase: 3, title: 'Technology Transfer', narrative: `Foreign firms often prefer to keep technology at home. Do you insist on technology transfer in FDI deals — requiring local partners, training, or licensing — so that know-how stays and spreads? It could build domestic capacity but may deter some investors.`, choices: [{ id: 'yes', text: 'Insist on transfer', consequence: 'Local firms gain know-how; some investors hesitate.', effects: { sovereignty: 12, economicStrength: 8 } }, { id: 'no', text: 'No', consequence: 'Investment flows freely but technology stays abroad.', effects: { economicStrength: 10 } }, { id: 'incentivize', text: 'Offer incentives for voluntary transfer, no mandates', consequence: 'Tax breaks and partnerships encourage spillovers without scaring off investors.', effects: { sovereignty: 5, economicStrength: 9 } }] },
  { phase: 3, title: 'Debt', narrative: `Debt is building — your investment push has been financed by borrowing. Do you slow investment to stabilise the books, or borrow more to keep growth going? Slowing may reassure creditors but cost momentum; borrowing may sustain growth but add to vulnerability.`, choices: [{ id: 'slow', text: 'Slow investment', consequence: 'Debt stabilises but momentum is lost.', effects: { debtBurden: -10, economicStrength: -5 } }, { id: 'borrow', text: 'Borrow more', consequence: 'Growth continues but vulnerability to creditors rises.', effects: { economicStrength: 12, debtBurden: 10 } }, { id: 'rebalance', text: 'Shift to domestic savings and revenue to fund growth', consequence: 'You raise taxes and encourage local bond issuance to reduce foreign debt.', effects: { debtBurden: -3, economicStrength: 4, sovereignty: 6 } }] },
  { phase: 3, title: 'Labor Rights', narrative: `Do you strengthen labour rights — collective bargaining, safety, job security — to ensure workers share in growth? It could improve living standards and domestic demand but may concern investors who prefer flexible labour markets.`, choices: [{ id: 'yes', text: 'Strengthen', consequence: 'Workers gain bargaining power and job security.', effects: { publicSupport: 15 } }, { id: 'no', text: 'No', consequence: 'Flexible labour markets attract investors.', effects: { economicStrength: 5 } }, { id: 'safety_first', text: 'Safety and minimums only — defer collective bargaining', consequence: 'You improve conditions and wages but limit union power.', effects: { publicSupport: 8, economicStrength: 8 } }] },
  { phase: 4, title: 'Mid-Term', narrative: `Industry is booming — growth is strong, perhaps too strong. Inflation is picking up. Do you cool the economy with tighter policy to prevent overheating, or let it run and bet on continued expansion? Cooling may prevent a crash but could slow the boom; letting it run may maximise growth but risk a hard landing.`, choices: [{ id: 'cool', text: 'Cool the economy', consequence: 'Overheating risks ease but growth moderates.', effects: { priceStability: 10, economicStrength: -3 } }, { id: 'run', text: 'Let it run', consequence: 'The boom continues; inflation and imbalances build.', effects: { economicStrength: 15, priceStability: -8 } }, { id: 'targeted', text: 'Targeted tightening — curb speculation, keep productive credit', consequence: 'You cool asset bubbles while sustaining real investment.', effects: { priceStability: 6, economicStrength: 5 } }] },
  { phase: 4, title: 'Inequality', narrative: `Growth is uneven — some regions and groups have gained much more than others. Do you redistribute — taxing the winners to fund transfers, services, and investment in lagging areas — or let growth continue without intervention? Redistribution may slow headline growth but spread benefits; growth-first may leave inequality to fester.`, choices: [{ id: 'yes', text: 'Redistribute', consequence: 'Taxes and transfers spread gains more widely.', effects: { publicSupport: 15, economicStrength: 2 } }, { id: 'no', text: 'No', consequence: 'Growth continues but inequality deepens.', effects: { economicStrength: 8 } }, { id: 'invest', text: 'Invest in lagging regions — no wealth tax', consequence: 'You fund infrastructure and schools in poor areas without touching winners.', effects: { publicSupport: 10, economicStrength: 5 } }] },
  { phase: 4, title: 'Geopolitical Economy', narrative: `Analysts of geopolitical economy argue that states shape outcomes — industrial policy, trade strategy, and financial regulation are tools, not constraints. Do you use industrial policy aggressively, steering investment and protecting strategic sectors, or keep intervention modest? Aggressive policy may accelerate development but risks inefficiency; modesty may be safer but slower.`, choices: [{ id: 'yes', text: 'Aggressive industrial policy', consequence: 'Strategic sectors are steered toward national goals.', effects: { economicStrength: 12, sovereignty: 10 } }, { id: 'no', text: 'Modest intervention', consequence: 'The state steps back; growth is slower but less directed.', effects: { economicStrength: 6 } }, { id: 'catalytic', text: 'Catalytic state — convene, subsidise R&D, leave production to firms', consequence: 'You de-risk innovation and link firms to markets without picking winners.', effects: { economicStrength: 9, sovereignty: 5 } }] },
  { phase: 4, title: 'Exchange Rate', narrative: `A competitive exchange rate — keeping the currency relatively weak — can boost exports by making your goods cheaper abroad. Do you manage the rate for export competitiveness, or let it float and accept whatever the market delivers? Management may support industry but can distort allocation; floating may be cleaner but less predictable.`, choices: [{ id: 'yes', text: 'Manage rate', consequence: 'A weak currency boosts exports and industry.', effects: { economicStrength: 10 } }, { id: 'no', text: 'Let it float', consequence: 'The market sets the rate; outcomes are less predictable.', effects: { sovereignty: 5 } }, { id: 'band', text: 'Managed float within a band', consequence: 'You dampen volatility while allowing some market adjustment.', effects: { economicStrength: 7, sovereignty: 6 } }] },
  { phase: 5, title: 'Year Two', narrative: `Growth is strong. Do you consolidate — locking in gains, managing risks, perhaps easing off the accelerator — or accelerate, pushing for more? Consolidation may prevent overreach; acceleration may capture more of the moment.`, choices: [{ id: 'consolidate', text: 'Consolidate', consequence: 'Risks are managed; growth moderates but stabilises.', effects: { priceStability: 8 } }, { id: 'accelerate', text: 'Accelerate', consequence: 'You push for more; growth surges but imbalances grow.', effects: { economicStrength: 12 } }, { id: 'selective', text: 'Accelerate winners, consolidate laggards', consequence: 'You double down on sectors that are delivering and trim the rest.', effects: { economicStrength: 9, priceStability: 3 } }] },
  { phase: 5, title: 'Dollar Dependence', narrative: `Trade in dollars ties you to US financial infrastructure — and its sanctions, surveillance, and policy. Do you reduce dollar dependence by promoting alternative currencies and payment systems, or accept it as the cost of integration? Reducing dependence may expand options but complicate trade; accepting it may be simpler but leaves you exposed.`, choices: [{ id: 'yes', text: 'Reduce dependence', consequence: 'Alternative currencies and payment systems expand options.', effects: { sovereignty: 12 } }, { id: 'no', text: 'No', consequence: 'Dollar integration deepens; you remain exposed to US policy.', effects: { economicStrength: 5, sovereignty: -5 } }, { id: 'parallel', text: 'Build parallel systems while keeping dollar channels', consequence: 'You add alternatives for regional trade but retain dollar access.', effects: { sovereignty: 6, economicStrength: 6 } }] },
  { phase: 5, title: 'Legacy', narrative: `What development model do you leave? A sovereign industrialiser — state-led, less dependent on foreign capital, building domestic capacity? Or an integrated industrialiser — growing through connection to global markets, accepting some dependence for the sake of growth?`, choices: [{ id: 'sovereign', text: 'Sovereign industrializer', consequence: 'Donghai leaves a legacy of state-led, less dependent development.', effects: { sovereignty: 12, economicStrength: 10 } }, { id: 'integrated', text: 'Integrated industrializer', consequence: 'Donghai embraces global integration for growth.', effects: { economicStrength: 12 } }, { id: 'pragmatic', text: 'Pragmatic integration — integrate where it helps, protect where it matters', consequence: 'Donghai leaves a mixed model suited to a multipolar world.', effects: { sovereignty: 6, economicStrength: 10 } }] },
  { phase: 5, title: 'Final Decision', narrative: `Your last decision for Donghai. The path you choose will shape whether industrialisation serves your people or foreign capital — and how history judges your development.`, choices: [{ id: 'shared', text: 'Shared growth legacy', consequence: 'History remembers Donghai for inclusive development.', effects: { publicSupport: 12, economicStrength: 8 } }, { id: 'industrial', text: 'Industrial powerhouse legacy', consequence: 'History remembers Donghai for its industrial might.', effects: { economicStrength: 12 } }, { id: 'balanced', text: 'Balanced legacy', consequence: 'History remembers Donghai for balancing growth and equity.', effects: { economicStrength: 8, publicSupport: 8 } }] },
  { phase: 1, title: 'Accelerating Investment', narrative: `You have chosen full speed ahead. The question is where to direct the surge. Do you prioritise export-oriented industry — discipline through global competition — or domestic-oriented industry — building the home market first? Exports bring foreign exchange; domestic focus may build more resilient demand.`, choices: [{ id: 'export', text: 'Export-oriented', consequence: 'Global competition disciplines firms; foreign exchange flows in.', effects: { economicStrength: 12, sovereignty: -5 }, nextBlock: 21 }, { id: 'domestic', text: 'Domestic-oriented', consequence: 'The home market is built first; demand becomes more resilient.', effects: { economicStrength: 10, publicSupport: 5 }, nextBlock: 21 }, { id: 'both', text: 'Export-oriented now, earmark gains for domestic capacity', consequence: 'You chase foreign exchange first while planning to invest in the home market.', effects: { economicStrength: 11, publicSupport: 2, sovereignty: -2 }, nextBlock: 21 }] },
  { phase: 1, title: 'Sharing the Gains', narrative: `You have chosen to share the gains. The question is how. Do you prioritise wage increases and labour rights, or public services — healthcare, education, pensions? Wages put money in pockets; services build collective welfare. Both can support demand.`, choices: [{ id: 'wages', text: 'Wages and labour rights', consequence: 'Workers see higher pay and stronger protections.', effects: { publicSupport: 12, economicStrength: 3 } }, { id: 'services', text: 'Public services', consequence: 'Healthcare, education, and pensions expand.', effects: { publicSupport: 10, debtBurden: 5 } }, { id: 'mixed', text: 'Modest wage gains plus targeted services for the poor', consequence: 'You spread benefits across both channels with limited fiscal strain.', effects: { publicSupport: 10, economicStrength: 5, debtBurden: 2 } }] },
];

const endings: LongFormEnding[] = [
  { id: 'victory', endingType: 'victory', title: 'Industrialisation with a Human Face', endingNarrative: `You industrialised while sharing the gains. Donghai has grown without losing its soul.` },
  { id: 'partial', endingType: 'partial_victory', title: 'Industrial Powerhouse', endingNarrative: `You built industry. Growth was strong. The distribution of gains remains contested.` },
  { id: 'defeat', endingType: 'defeat', title: 'Dependent Development', endingNarrative: `Growth came but in ways that serve foreign capital. The struggle for sovereign development continues.` },
];

export function createNarrativeTree(options?: { shuffle?: boolean; seed?: number }) {
  return createLongFormTree(
    blocks,
    endings,
    (i) => (i === 0 ? 0 : i === 1 ? 1 : 2),
    {
      shuffleBlocks: options?.shuffle ?? true,
      seed: options?.seed,
      blockPool: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
      blockPoolCount: 13,
    },
  );
}
