import type { DecisionBlock, LongFormEnding } from '../long-form-tree';
import { createLongFormTree } from '../long-form-tree';

/**
 * Rust Belt Revival — Federal Republic of Nordmark (20 decisions)
 */
const blocks: DecisionBlock[] = [
  {
    phase: 1,
    title: 'The Rust Belt Challenge',
    narrative: `You lead the Federal Republic of Nordmark. Factories have closed, jobs have moved away. Some analysts argue that prosperity in the North has long rested on value transferred from the South through trade and finance. Others point out that when markets are left to run unchecked, society eventually pushes back — a "double movement" that was perhaps delayed here. Research on inequality suggests that when returns to capital outpace growth, wealth concentrates. What do you do first?`,
    choices: [
      { id: 'industrial', text: 'Launch industrial policy', consequence: 'You bet on factories.', effects: { economicStrength: 8, employment: 10, debtBurden: 5 }, nextBlock: 20 },
      { id: 'services', text: 'Invest in services and retraining', consequence: 'You focus on human capital.', effects: { employment: 5, publicSupport: 8, economicStrength: 5 }, nextBlock: 21 },
      { id: 'austerity', text: 'Cut spending and wait', consequence: 'You take a hands-off approach.', effects: { debtBurden: -10, publicSupport: -15, employment: -5 } },
    ],
  },
  { phase: 1, title: 'First Moves', narrative: `Your initial policy has drawn attention. The affected towns want to be heard. Do you hold a summit with mayors of the hardest-hit regions — a visible signal that you take their plight seriously — or work through existing bureaucratic channels? The summit could build political capital; the channels might be faster but less visible.`, choices: [{ id: 'summit', text: 'Hold a summit', consequence: '', effects: { publicSupport: 8 } }, { id: 'channels', text: 'Work through channels', consequence: '', effects: { economicStrength: 3 } }] },
  { phase: 1, title: 'Energy Costs', narrative: `Energy prices are squeezing what remains of local industry. Factories that survived the offshoring wave now face another threat: they cannot compete when energy costs spike. Do you subsidize industrial energy to keep them afloat, or let the market decide — accepting that some will close? Subsidies cost the treasury; market logic may cost jobs.`, choices: [{ id: 'subsidize', text: 'Subsidize industrial energy', consequence: '', effects: { economicStrength: 8, debtBurden: 8 } }, { id: 'market', text: 'Let the market decide', consequence: '', effects: { debtBurden: -5, economicStrength: -5 } }] },
  { phase: 1, title: 'Training Programs', narrative: `Retraining enrollment is low. Workers who lost factory jobs are reluctant to sign up — the programs feel abstract, and many cannot afford to study without income. Do you add stipends for trainees so they can afford to retrain, or improve placement incentives so employers have more reason to hire graduates? Stipends cost more but may boost enrollment; placement incentives target outcomes.`, choices: [{ id: 'stipends', text: 'Add trainee stipends', consequence: '', effects: { employment: 8, publicSupport: 10, debtBurden: 5 } }, { id: 'placement', text: 'Improve placement incentives', consequence: '', effects: { employment: 5, debtBurden: 2 } }] },
  { phase: 2, title: 'Green Investment', narrative: `Battery manufacturers are interested in locating in the region — drawn by skilled workers, space, and the promise of green industrial policy. Do you offer tax breaks to attract them, or direct grants? Tax breaks cost less upfront but reduce revenue for years; grants are more visible and can be targeted to specific investments.`, choices: [{ id: 'tax', text: 'Offer tax breaks', consequence: '', effects: { economicStrength: 10, debtBurden: 3 } }, { id: 'grants', text: 'Direct grants', consequence: '', effects: { economicStrength: 12, debtBurden: 8 } }] },
  { phase: 2, title: 'Import Competition', narrative: `Cheap imports continue to undercut local producers. Some argue that these prices reflect global wage hierarchies — goods made where labour is cheap and regulations weak. Do you raise tariffs on key goods to protect domestic industry, or stay open and accept the competition? Tariffs may save jobs but raise prices; openness may lower prices but cost more jobs.`, choices: [{ id: 'tariffs', text: 'Raise tariffs', consequence: '', effects: { economicStrength: 5, publicSupport: 5, priceStability: -5 } }, { id: 'open', text: 'Stay open', consequence: '', effects: { economicStrength: -3, priceStability: 5 } }] },
  { phase: 2, title: 'Inequality Focus', narrative: `Wealth is concentrating in your cities while the rust belt hollows out. Studies of wealth concentration suggest that when capital earns more than the economy grows, inequality deepens. Do you propose a wealth tax to fund redistribution and public investment, or focus on jobs — betting that employment will lift people without touching accumulated wealth?`, choices: [{ id: 'wealth_tax', text: 'Propose wealth tax', consequence: '', effects: { publicSupport: 12, debtBurden: -5 } }, { id: 'jobs', text: 'Focus on jobs', consequence: '', effects: { employment: 10, economicStrength: 8 } }] },
  { phase: 2, title: 'Service Sector', narrative: `The service sector is growing — retail, care work, logistics — but wages are low. Many of these jobs replaced the factory work that once paid a living wage. Do you push for minimum wage increases to lift workers out of poverty, or let the sector evolve without intervention? Higher wages may reduce some employment but improve living standards for those who keep jobs.`, choices: [{ id: 'min_wage', text: 'Push for minimum wage', consequence: '', effects: { publicSupport: 10, employment: -3 } }, { id: 'evolve', text: 'Let it evolve', consequence: '', effects: { employment: 5, publicSupport: -5 } }] },
  { phase: 3, title: 'Infrastructure', narrative: `Roads and broadband are inadequate in the rural and ex-industrial areas. Firms considering relocation cite this as a barrier. Do you launch a major infrastructure program — roads, rail, fibre — or make only modest improvements? A major program could attract investment but adds to debt; modest steps cost less but may not be enough to change minds.`, choices: [{ id: 'launch', text: 'Launch major program', consequence: '', effects: { economicStrength: 10, debtBurden: 10, publicSupport: 8 } }, { id: 'modest', text: 'Modest improvements only', consequence: '', effects: { economicStrength: 4, debtBurden: 3 } }] },
  { phase: 3, title: 'Union Relations', narrative: `Unions want sectoral bargaining — negotiating wages and conditions across whole industries rather than firm by firm. Supporters say it raises floor wages and reduces inequality; critics say it rigidifies labour markets and hurts competitiveness. Do you support it or resist? Supporting could strengthen labour's hand; resisting may please business but alienate workers.`, choices: [{ id: 'support', text: 'Support sectoral bargaining', consequence: '', effects: { publicSupport: 12, economicStrength: 2 } }, { id: 'resist', text: 'Resist', consequence: '', effects: { economicStrength: 5, publicSupport: -10 } }] },
  { phase: 3, title: 'Housing Crisis', narrative: `Factory towns have empty homes — workers left when the plants closed. Cities have shortages — people who stayed or moved for service jobs cannot find affordable housing. Do you fund relocation assistance to help people move where jobs are, or build new housing in cities? Relocation may depopulate towns further; building in cities may draw more people but also create jobs.`, choices: [{ id: 'relocation', text: 'Fund relocation', consequence: '', effects: { employment: 5, publicSupport: 5 } }, { id: 'cities', text: 'Build in cities', consequence: '', effects: { economicStrength: 8, publicSupport: 3 } }] },
  { phase: 3, title: 'Budget Pressure', narrative: `Debt is rising. Your industrial policy, energy subsidies, and infrastructure spending have added up. Do you cut other programs to fund industrial policy — shifting money from social services or elsewhere — or borrow more? Cutting may satisfy creditors but cost political support; borrowing keeps the program going but increases debt.`, choices: [{ id: 'cut', text: 'Cut other programs', consequence: '', effects: { debtBurden: -8, publicSupport: -5 } }, { id: 'borrow', text: 'Borrow more', consequence: '', effects: { debtBurden: 8, economicStrength: 8 } }] },
  { phase: 4, title: 'Mid-Term Review', narrative: `Some factories have opened. Unemployment has fallen slightly. Early signs suggest the policy is working, but it is expensive. Do you double down — expand the program and bet on continued success — or consolidate, trimming spending and locking in gains? Doubling down could accelerate revival but risks overreach; consolidating may reassure markets but slow momentum.`, choices: [{ id: 'double', text: 'Double down', consequence: '', effects: { economicStrength: 12, debtBurden: 10 } }, { id: 'consolidate', text: 'Consolidate', consequence: '', effects: { debtBurden: -8, economicStrength: 2 } }] },
  { phase: 4, title: 'Skills Mismatch', narrative: `Employers say workers lack the skills they need — technical, digital, or industry-specific. Do you expand vocational education to train locals, or ease immigration to bring in workers who already have those skills? Vocational expansion takes time but builds local capacity; immigration is faster but may fuel resentment.`, choices: [{ id: 'vocational', text: 'Expand vocational education', consequence: '', effects: { employment: 10, debtBurden: 5 } }, { id: 'immigration', text: 'Ease immigration', consequence: '', effects: { economicStrength: 8, publicSupport: -5 } }] },
  { phase: 4, title: 'Regional Inequality', narrative: `The gap between thriving and declining regions is widening. Some towns are reviving; others are still hollowed out. Do you redistribute — taxing prosperous areas to fund investment in lagging ones — or focus on growth, betting that a rising tide will eventually lift all boats? Redistribution may slow growth in winners but help losers; growth-first may leave some behind.`, choices: [{ id: 'redistribute', text: 'Redistribute', consequence: '', effects: { publicSupport: 12, economicStrength: 2 } }, { id: 'growth', text: 'Focus on growth', consequence: '', effects: { economicStrength: 10, publicSupport: 2 } }] },
  { phase: 4, title: 'Energy Transition', narrative: `Coal plants are closing — ageing, uneconomic, or pressured by climate policy. The communities that depended on them face another wave of job losses. Do you fund a "just transition" — retraining, income support, and investment in new industries for affected workers — or let markets handle it? A just transition costs money but may prevent another rust belt; leaving it to markets may be cheaper but could deepen despair.`, choices: [{ id: 'just', text: 'Fund just transition', consequence: '', effects: { publicSupport: 15, employment: 5, debtBurden: 8 } }, { id: 'market', text: 'Let markets handle it', consequence: '', effects: { debtBurden: -5, publicSupport: -10 } }] },
  { phase: 5, title: 'Year Two', narrative: `Progress is visible but uneven. Some communities have turned a corner; others still struggle. Do you expand the program — more investment, more support — or declare victory and scale back, letting the private sector take over? Expansion may deepen gains but add to debt; declaring victory may please fiscal hawks but leave unfinished business.`, choices: [{ id: 'expand', text: 'Expand the program', consequence: '', effects: { economicStrength: 10, debtBurden: 8 } }, { id: 'declare', text: 'Declare victory', consequence: '', effects: { debtBurden: -5, publicSupport: 5 } }] },
  { phase: 5, title: 'Export Push', narrative: `New manufacturers — including some of the green investments you attracted — want export support: trade missions, financing, diplomatic backing. Do you provide it? Export growth could create jobs and bring in foreign exchange, but it also ties the region to global demand.`, choices: [{ id: 'yes', text: 'Provide export support', consequence: '', effects: { economicStrength: 12 } }, { id: 'no', text: 'Decline', consequence: '', effects: { debtBurden: -3 } }] },
  { phase: 5, title: 'Labor Shortage', narrative: `Some sectors report labour shortages — not enough workers with the right skills or willingness to work at current wages. Do you support wage increases to attract workers, or focus on training to expand the labour pool? Higher wages may draw people back into the workforce; training takes longer but may be more sustainable.`, choices: [{ id: 'wages', text: 'Support wage increases', consequence: '', effects: { publicSupport: 10, economicStrength: 3 } }, { id: 'training', text: 'Focus on training', consequence: '', effects: { employment: 8 } }] },
  { phase: 5, title: 'Final Quarter', narrative: `Your term ends. What legacy do you leave for the rust belt? An industrial revival — factories reopened, jobs returned, hope restored? A managed transition — not everyone saved, but many found new paths? Or a mixed record — some gains, some losses, the struggle continues?`, choices: [{ id: 'industrial', text: 'An industrial revival', consequence: '', effects: { economicStrength: 10, employment: 10 } }, { id: 'transition', text: 'A managed transition', consequence: '', effects: { publicSupport: 8, economicStrength: 5 } }, { id: 'mixed', text: 'A mixed record', consequence: '', effects: { debtBurden: -5 } }] },
  { phase: 1, title: 'Industrial Policy Launch', narrative: `You have committed to industrial policy. The question is how to target it. Do you focus on attracting new industries — green tech, advanced manufacturing — or on reviving what remains of the old industrial base? The first may create more jobs long-term; the second may save jobs now.`, choices: [{ id: 'new', text: 'Focus on new industries', consequence: '', effects: { economicStrength: 10, employment: 5 }, nextBlock: 1 }, { id: 'revive', text: 'Revive existing base', consequence: '', effects: { employment: 10, economicStrength: 5 }, nextBlock: 1 }] },
  { phase: 1, title: 'Services and Retraining', narrative: `You have committed to services and retraining. The question is scale. Do you launch a major program — free vocational training, stipends for trainees — or a modest one that targets the most employable first? The first costs more but reaches more people; the second is cheaper but may leave many behind.`, choices: [{ id: 'major', text: 'Major program', consequence: '', effects: { employment: 10, publicSupport: 10, debtBurden: 8 }, nextBlock: 1 }, { id: 'modest', text: 'Modest program', consequence: '', effects: { employment: 5, debtBurden: 2 }, nextBlock: 1 }] },
];

const endings: LongFormEnding[] = [
  { id: 'victory', endingType: 'victory', title: 'Rust Belt Revival', endingNarrative: `You revived industry through targeted policy. Factories have reopened. Jobs have returned. The rust belt is showing signs of life.` },
  { id: 'partial', endingType: 'partial_victory', title: 'Managed Transition', endingNarrative: `You eased the transition. Not everyone was saved, but many found new paths. The outcome is mixed but real.` },
  { id: 'defeat', endingType: 'defeat', title: 'Decline Continues', endingNarrative: `The hands-off approach left many communities behind. Debt fell, but so did hope. The rust belt's struggle continues.` },
];

const { getNode } = createLongFormTree(blocks, endings, (i) => (i === 0 ? 0 : i === 1 ? 1 : 2));
export { getNode };
