import type { DecisionBlock, LongFormEnding } from '../long-form-tree';
import { createLongFormTree } from '../long-form-tree';

/**
 * Under Sanctions — Republic of Persea (20 decisions)
 */
const blocks: DecisionBlock[] = [
  {
    phase: 1,
    title: 'Under Sanctions',
    narrative: `You lead the Republic of Persea. Some analysts understand imperialism as a system — and sanctions as its discipline, punishing those who step out of line. Research on sanctions shows they can deindustrialise economies, destroying productive capacity. Scholars of geopolitical economy argue that a multipolar world offers alternatives — new partners, new payment systems, new paths. What do you do first?`,
    choices: [
      { id: 'alternative', text: 'Pivot to alternative partners', consequence: 'New trade partners emerge, though Western relations cool.', effects: { economicStrength: 8, sovereignty: 5, internationalStanding: -5 }, nextBlock: 20 },
      { id: 'self_reliance', text: 'Build self-reliance', consequence: 'Domestic production and local supply chains begin to replace imports.', effects: { sovereignty: 15, economicStrength: 5, publicSupport: 8 }, nextBlock: 21 },
      { id: 'negotiate', text: 'Pursue negotiations', consequence: 'Diplomatic channels open, but concessions may be demanded.', effects: { internationalStanding: 5, publicSupport: 3, sovereignty: -5 } },
    ],
  },
  { phase: 1, title: 'Payment Systems', narrative: `Sanctions often work through the financial system — cutting off access to dollar clearing, correspondent banks, and SWIFT. Do you build alternative payment systems to bypass them — bilateral arrangements, regional clearing, non-dollar trade? It could restore some trade but requires coordination and may be incomplete.`, choices: [{ id: 'yes', text: 'Build alternatives', consequence: 'Bilateral and regional clearing arrangements restore some trade flows.', effects: { sovereignty: 12, economicStrength: 5 } }, { id: 'no', text: 'No', consequence: 'Dollar dependence leaves trade vulnerable to further disruption.', effects: { economicStrength: -3, sovereignty: -5 } }, { id: 'regional', text: 'Join existing regional payment system', consequence: 'You plug into a regional clearing network, gaining trade access with less upfront cost.', effects: { sovereignty: 7, economicStrength: 4 } }] },
  { phase: 1, title: 'Import Substitution', narrative: `Scholars of transition economics argue that when external supplies are cut off, you must produce at home. Do you push import substitution — building domestic capacity for goods you can no longer import? It could reduce dependence but requires investment and time; some goods may be hard to replace.`, choices: [{ id: 'yes', text: 'Push substitution', consequence: 'Domestic factories ramp up to replace banned imports.', effects: { sovereignty: 15, economicStrength: 8 } }, { id: 'no', text: 'No', consequence: 'Shortages persist as critical goods remain unavailable.', effects: { economicStrength: -4, publicSupport: -3 } }, { id: 'selective', text: 'Selectively substitute only critical goods', consequence: 'You focus capacity on essentials like medicines and food while sourcing the rest where possible.', effects: { sovereignty: 8, economicStrength: 4 } }] },
  { phase: 1, title: 'Secondary Sanctions', narrative: `Partners fear secondary sanctions — punishment for trading with you. Do you deepen ties with a few willing partners who are less vulnerable to pressure, or diversify widely to spread risk? Deepening may build stronger relationships but concentrates dependence; diversifying may be more resilient but thinner.`, choices: [{ id: 'deepen', text: 'Deepen with few', consequence: 'Stronger ties with willing partners secure reliable supply lines.', effects: { economicStrength: 10, sovereignty: 8 } }, { id: 'diversify', text: 'Diversify widely', consequence: 'Broader networks reduce vulnerability to any single partner.', effects: { economicStrength: 6, sovereignty: 5 } }, { id: 'quiet', text: 'Pursue quiet bilateral deals', consequence: 'Low-profile arrangements with pragmatic partners keep goods flowing without drawing attention.', effects: { economicStrength: 7, sovereignty: 6 } }] },
  { phase: 2, title: 'Kadri\'s Warning', narrative: `Kadri: sanctions destroy productive capacity. Do you protect strategic industries?`, choices: [{ id: 'yes', text: 'Protect strategic industries', consequence: 'Key sectors receive subsidies and priority access to scarce inputs.', effects: { sovereignty: 12, economicStrength: 8 } }, { id: 'no', text: 'No', consequence: 'Strategic capacity erodes as sanctions bite deeper.', effects: { economicStrength: -5, sovereignty: -3 } }, { id: 'selective', text: 'Protect only critical sectors', consequence: 'You shield defence and energy while letting others adapt on their own.', effects: { sovereignty: 7, economicStrength: 5 } }] },
  { phase: 2, title: 'Rationing', narrative: `Research on managing scarcity suggests that when supplies are short, rationing can ensure essentials reach everyone rather than flowing to those who can pay most. Do you introduce rationing for food, medicine, and fuel? It may ensure fairness but can be administratively complex and politically fraught.`, choices: [{ id: 'yes', text: 'Introduce rationing', consequence: 'Essential goods reach more households, though queues and bureaucracy grow.', effects: { publicSupport: 5, economicStrength: 2 } }, { id: 'no', text: 'No', consequence: 'The wealthy hoard while the poor go without.', effects: { publicSupport: -5 } }, { id: 'partial', text: 'Ration only medicine and fuel', consequence: 'Critical goods are shared; food remains in the market for those who can pay.', effects: { publicSupport: 2, economicStrength: 3 } }] },
  { phase: 2, title: 'South-South Cooperation', narrative: `Scholars of multipolarity argue that South-South cooperation can reduce dependence on the sanctioning bloc. Do you prioritise trade and ties with other developing countries, building alternatives to Northern markets and finance? It could expand options but may mean trading with partners who have less to offer in the short term.`, choices: [{ id: 'yes', text: 'Prioritize South-South', consequence: 'New trade routes and partnerships reduce dependence on the North.', effects: { sovereignty: 10, economicStrength: 6 } }, { id: 'no', text: 'No', consequence: 'Continued reliance on Northern markets leaves you exposed.', effects: { sovereignty: -4, economicStrength: -2 } }, { id: 'quiet', text: 'Pursue quiet bilateral deals', consequence: 'Low-profile agreements with Southern partners expand options without grand declarations.', effects: { sovereignty: 5, economicStrength: 4 } }] },
  { phase: 2, title: 'Domestic Production', narrative: `Sanctioned goods — technology, spare parts, medicines — are hard to get. Do you invest heavily in domestic production to replace them? It could build resilience but is expensive and some things may be impossible to replicate.`, choices: [{ id: 'yes', text: 'Invest heavily', consequence: 'Domestic factories and labs begin producing formerly imported goods.', effects: { sovereignty: 15, economicStrength: 10, debtBurden: 10 } }, { id: 'modest', text: 'Modest investment', consequence: 'Some capacity is built, but gaps remain.', effects: { economicStrength: 5 } }, { id: 'reverse', text: 'Reverse-engineer and adapt grey-market goods', consequence: 'You invest in copying and adapting what flows through informal channels.', effects: { sovereignty: 8, economicStrength: 6 } }] },
  { phase: 3, title: 'Capital Controls', narrative: `Capital is fleeing — sanctions and uncertainty are driving money out. Do you impose strict capital controls to stem the flow and keep resources at home? It could stabilise the economy but may deter future investment and complicate trade.`, choices: [{ id: 'yes', text: 'Impose strict controls', consequence: 'Capital flight slows and reserves stabilise.', effects: { sovereignty: 12 } }, { id: 'no', text: 'No', consequence: 'Some investment stays, but outflows continue.', effects: { economicStrength: 3 } }, { id: 'selective', text: 'Targeted controls on strategic sectors', consequence: 'You limit outflows from key industries while leaving other flows mostly free.', effects: { sovereignty: 7, economicStrength: 2 } }] },
  { phase: 3, title: 'Barter Trade', narrative: `Dollar-based trade is restricted. Do you pursue barter and non-dollar trade — swapping goods directly or using alternative currencies — to keep commerce flowing? It could bypass financial sanctions but is less efficient and may be limited in scale.`, choices: [{ id: 'yes', text: 'Pursue barter', consequence: 'Goods-for-goods deals and alternative currencies keep commerce alive.', effects: { sovereignty: 10, economicStrength: 5 } }, { id: 'no', text: 'No', consequence: 'Trade remains constrained by dollar restrictions.', effects: { economicStrength: -4, sovereignty: -3 } }, { id: 'limited', text: 'Allow barter only for critical imports', consequence: 'Essential goods flow through swaps; the rest awaits dollar access.', effects: { sovereignty: 5, economicStrength: 2 } }] },
  { phase: 3, title: 'Negotiations', narrative: `Do you offer concessions to ease sanctions — policy changes, commitments, compromises that might satisfy the sanctioning powers? It could open the door to relief but may cost sovereignty and legitimacy at home.`, choices: [{ id: 'yes', text: 'Offer concessions', consequence: 'Talks progress, but critics accuse you of selling out.', effects: { internationalStanding: 10, sovereignty: -12 } }, { id: 'no', text: 'Hold firm', consequence: 'Sanctions remain, but your stance wins respect at home.', effects: { sovereignty: 10 } }, { id: 'quiet', text: 'Back-channel talks without public commitments', consequence: 'Quiet diplomacy explores options without binding your government.', effects: { internationalStanding: 3, sovereignty: 3 } }] },
  { phase: 3, title: 'Smuggling', narrative: `Informal channels have emerged — goods flowing through third countries, grey markets, networks that bypass sanctions. Do you tolerate them to keep supplies flowing, or crack down to maintain control and avoid provoking the sanctioning powers? Tolerance may ease shortages but could undermine your position; cracking down may please critics but hurt ordinary people.`, choices: [{ id: 'tolerate', text: 'Tolerate', consequence: 'Goods flow through grey channels, easing shortages.', effects: { economicStrength: 8, publicSupport: 5 } }, { id: 'crack', text: 'Crack down', consequence: 'Smuggling declines, but supplies tighten.', effects: { sovereignty: 5 } }, { id: 'regulate', text: 'Regulate informally — tax and steer grey flows', consequence: 'You extract revenue and channel informal trade toward priority needs.', effects: { economicStrength: 5, sovereignty: 3 } }] },
  { phase: 4, title: 'Mid-Term', narrative: `You have adapted — the economy has found ways to function under sanctions. Do you deepen self-reliance, investing more in domestic production and alternative partners, or seek a deal with the sanctioning powers to ease the pressure? Deepening may build lasting resilience; a deal could bring relief but at a cost.`, choices: [{ id: 'deepen', text: 'Deepen self-reliance', consequence: 'Domestic capacity and alternative partners grow stronger.', effects: { sovereignty: 15, economicStrength: 8 } }, { id: 'deal', text: 'Seek a deal', consequence: 'Negotiations intensify; relief may come at a price.', effects: { internationalStanding: 8, sovereignty: -8 } }, { id: 'consolidate', text: 'Consolidate what works, avoid overreach', consequence: 'You stabilise current arrangements rather than doubling down or negotiating.', effects: { economicStrength: 5, publicSupport: 5 } }] },
  { phase: 4, title: 'Technology', narrative: `Sanctioned technology — chips, software, specialised equipment — is hard to replace. Do you invest in domestic R&D to build alternatives? It could reduce dependence over time but is costly and may take years to bear fruit.`, choices: [{ id: 'yes', text: 'Invest in R&D', consequence: 'Local labs and engineers work toward technological independence.', effects: { sovereignty: 12, economicStrength: 8 } }, { id: 'no', text: 'No', consequence: 'Technological gaps widen as sanctions block upgrades.', effects: { economicStrength: -5, sovereignty: -4 } }, { id: 'adapt', text: 'Adapt and refurbish existing technology', consequence: 'You extend the life of current equipment through maintenance and creative workarounds.', effects: { sovereignty: 6, economicStrength: 4 } }] },
  { phase: 4, title: 'Regional Bloc', narrative: `Do you form a regional bloc with other sanctioned or similarly constrained states — pooling resources, coordinating trade, building alternatives to the dominant order? It could strengthen your position but may also provoke further pressure.`, choices: [{ id: 'yes', text: 'Form bloc', consequence: 'Coordinated trade and pooled resources strengthen all members.', effects: { sovereignty: 12, economicStrength: 6 } }, { id: 'no', text: 'No', consequence: 'You face sanctions alone, with fewer options.', effects: { sovereignty: -4, economicStrength: -3 } }, { id: 'loose', text: 'Loose coordination without formal bloc', consequence: 'Informal alignment on trade and payments avoids the symbolism of a formal alliance.', effects: { sovereignty: 6, economicStrength: 4 } }] },
  { phase: 4, title: 'Humanitarian Exceptions', narrative: `Do you lobby for humanitarian exceptions — allowing food, medicine, and other essentials through the sanctions regime? It could ease suffering but may be seen as legitimising the sanctions themselves.`, choices: [{ id: 'yes', text: 'Lobby', consequence: 'Some humanitarian exemptions are granted, easing suffering.', effects: { publicSupport: 8, internationalStanding: 3 } }, { id: 'no', text: 'No', consequence: 'Essential goods remain blocked; public frustration grows.', effects: { publicSupport: -5, economicStrength: -2 } }, { id: 'ngos', text: 'Let NGOs and UN agencies lead the lobbying', consequence: 'Humanitarian access is pursued without official government endorsement.', effects: { publicSupport: 4, internationalStanding: 2 } }] },
  { phase: 5, title: 'Year Two', narrative: `The economy has adapted — new partners, new supply chains, new ways of operating. Do you consolidate, locking in what works and managing risks, or push for more — deeper self-reliance, broader alternatives? Consolidation may stabilise; pushing further may build resilience but could overstretch.`, choices: [{ id: 'consolidate', text: 'Consolidate', consequence: 'You lock in gains and reduce risk; stability improves.', effects: { publicSupport: 5, economicStrength: 3 } }, { id: 'push', text: 'Push for more', consequence: 'Further investment deepens self-reliance but stretches resources.', effects: { sovereignty: 10, economicStrength: 8 } }, { id: 'selective', text: 'Push only in sectors that are succeeding', consequence: 'You double down where results are strong and leave weak areas to stabilise.', effects: { economicStrength: 6, sovereignty: 5 } }] },
  { phase: 5, title: 'Legacy', narrative: `What model do you leave for Persea? A sovereign economy — self-reliant, with alternative partners and payment systems? Or a path toward reintegration — positioning for a deal that could ease sanctions and restore ties?`, choices: [{ id: 'sovereign', text: 'Sovereign economy', consequence: 'Persea is positioned for long-term independence.', effects: { sovereignty: 15 } }, { id: 'integrated', text: 'Reintegration path', consequence: 'Persea prepares for a future deal with the sanctioning bloc.', effects: { internationalStanding: 10 } }, { id: 'pragmatic', text: 'Pragmatic dual track', consequence: 'Persea maintains alternatives while keeping the door open to future dialogue.', effects: { sovereignty: 8, internationalStanding: 5 } }] },
  { phase: 5, title: 'Final Push', narrative: `Do you seek one more round of negotiations with the sanctioning powers — a last attempt to ease pressure before your term ends? It could bring relief or leave you with nothing to show for the effort.`, choices: [{ id: 'yes', text: 'Seek negotiations', consequence: 'One more round of talks begins; outcomes uncertain.', effects: { internationalStanding: 8 } }, { id: 'no', text: 'No', consequence: 'You leave office without further concessions.', effects: { sovereignty: 8 } }, { id: 'handover', text: 'Leave the option open for your successor', consequence: 'You document negotiating channels but do not commit to talks yourself.', effects: { internationalStanding: 3, sovereignty: 4 } }] },
  { phase: 5, title: 'Final Decision', narrative: `Your last decision for Persea. The path you choose will shape whether the country survives sanctions with sovereignty intact — or finds a way back into the fold.`, choices: [{ id: 'sovereign', text: 'Sovereign path', consequence: 'Persea emerges self-reliant, with new partners and systems.', effects: { sovereignty: 12, economicStrength: 6 } }, { id: 'negotiated', text: 'Negotiated path', consequence: 'Persea seeks reintegration and relief from sanctions.', effects: { internationalStanding: 10 } }, { id: 'mixed', text: 'Mixed path', consequence: 'Persea balances sovereignty with pragmatic engagement.', effects: { sovereignty: 8, economicStrength: 6 } }] },
  { phase: 1, title: 'Finding New Partners', narrative: `You have pivoted to alternative partners. The question is which. Do you prioritise regional neighbours — building a bloc of similarly constrained states — or seek bilateral deals with major powers outside the sanctioning coalition? Regional blocs may be more stable; bilateral deals may bring faster relief.`, choices: [{ id: 'regional', text: 'Regional bloc', consequence: 'Neighbouring states coordinate trade and mutual support.', effects: { sovereignty: 10, economicStrength: 5 }, nextBlock: 1 }, { id: 'bilateral', text: 'Bilateral deals', consequence: 'Major powers outside the coalition offer faster relief.', effects: { economicStrength: 8, sovereignty: -3 }, nextBlock: 1 }, { id: 'hybrid', text: 'Mix regional coordination with key bilateral ties', consequence: 'You secure regional backing while pursuing select deals with major powers.', effects: { sovereignty: 6, economicStrength: 6 }, nextBlock: 1 }] },
  { phase: 1, title: 'Building Self-Reliance', narrative: `You have chosen self-reliance. The question is where to start. Do you prioritise import substitution — producing at home what you can no longer import — or domestic R&D to build technological independence? Substitution may be faster; R&D may be more transformative.`, choices: [{ id: 'substitution', text: 'Import substitution', consequence: 'Domestic production replaces key imports.', effects: { sovereignty: 12, economicStrength: 8 }, nextBlock: 1 }, { id: 'rd', text: 'Domestic R&D', consequence: 'Investment in local innovation begins to pay off.', effects: { sovereignty: 10, economicStrength: 5 }, nextBlock: 1 }, { id: 'balanced', text: 'Parallel track: substitution for essentials, R&D for tech', consequence: 'You tackle both fronts with limited resources spread across priorities.', effects: { sovereignty: 9, economicStrength: 6 }, nextBlock: 1 }] },
];

const endings: LongFormEnding[] = [
  { id: 'victory', endingType: 'victory', title: 'Sovereign Under Pressure', endingNarrative: `You built self-reliance under sanctions. Persea has found new paths and new partners.` },
  { id: 'partial', endingType: 'partial_victory', title: 'Adapted', endingNarrative: `You adapted. The economy has found ways to function. The path ahead remains difficult.` },
  { id: 'defeat', endingType: 'defeat', title: 'Isolation Deepens', endingNarrative: `Sanctions have taken their toll. The economy has contracted. The struggle continues.` },
];

export function createNarrativeTree(options?: { shuffle?: boolean; seed?: number }) {
  return createLongFormTree(
    blocks,
    endings,
    (i) => (i === 0 ? 0 : i === 1 ? 1 : 2),
    { shuffleBlocks: options?.shuffle ?? true, seed: options?.seed },
  );
}
