import type { DecisionBlock, LongFormEnding } from '../long-form-tree';
import { createLongFormTree } from '../long-form-tree';

/**
 * Under Sanctions — Republic of Persea (20 decisions)
 */
const blocks: DecisionBlock[] = [
  {
    phase: 1,
    title: 'Under Sanctions',
    narrative: `You lead the Republic of Persea. Some analysts understand imperialism as a system — and sanctions as its discipline, punishing those who step out of line. Research on sanctions shows they can deindustrialise economies, destroying productive capacity. Scholars of geopolitical economy argue that a multipolar world offers alternatives — new partners, new payment systems, new paths. What do you do first?`,
    choices: [
      { id: 'alternative', text: 'Pivot to alternative partners', consequence: '', effects: { economicStrength: 8, sovereignty: 5, internationalStanding: -5 }, nextBlock: 20 },
      { id: 'self_reliance', text: 'Build self-reliance', consequence: '', effects: { sovereignty: 15, economicStrength: 5, publicSupport: 8 }, nextBlock: 21 },
      { id: 'negotiate', text: 'Pursue negotiations', consequence: '', effects: { internationalStanding: 5, publicSupport: 3, sovereignty: -5 } },
    ],
  },
  { phase: 1, title: 'Payment Systems', narrative: `Sanctions often work through the financial system — cutting off access to dollar clearing, correspondent banks, and SWIFT. Do you build alternative payment systems to bypass them — bilateral arrangements, regional clearing, non-dollar trade? It could restore some trade but requires coordination and may be incomplete.`, choices: [{ id: 'yes', text: 'Build alternatives', consequence: '', effects: { sovereignty: 12, economicStrength: 5 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 1, title: 'Import Substitution', narrative: `Scholars of transition economics argue that when external supplies are cut off, you must produce at home. Do you push import substitution — building domestic capacity for goods you can no longer import? It could reduce dependence but requires investment and time; some goods may be hard to replace.`, choices: [{ id: 'yes', text: 'Push substitution', consequence: '', effects: { sovereignty: 15, economicStrength: 8 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 1, title: 'Secondary Sanctions', narrative: `Partners fear secondary sanctions — punishment for trading with you. Do you deepen ties with a few willing partners who are less vulnerable to pressure, or diversify widely to spread risk? Deepening may build stronger relationships but concentrates dependence; diversifying may be more resilient but thinner.`, choices: [{ id: 'deepen', text: 'Deepen with few', consequence: '', effects: { economicStrength: 10, sovereignty: 8 } }, { id: 'diversify', text: 'Diversify widely', consequence: '', effects: { economicStrength: 6, sovereignty: 5 } }] },
  { phase: 2, title: 'Kadri\'s Warning', narrative: `Kadri: sanctions destroy productive capacity. Do you protect strategic industries?`, choices: [{ id: 'yes', text: 'Protect strategic industries', consequence: '', effects: { sovereignty: 12, economicStrength: 8 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 2, title: 'Rationing', narrative: `Research on managing scarcity suggests that when supplies are short, rationing can ensure essentials reach everyone rather than flowing to those who can pay most. Do you introduce rationing for food, medicine, and fuel? It may ensure fairness but can be administratively complex and politically fraught.`, choices: [{ id: 'yes', text: 'Introduce rationing', consequence: '', effects: { publicSupport: 5, economicStrength: 2 } }, { id: 'no', text: 'No', consequence: '', effects: { publicSupport: -5 } }] },
  { phase: 2, title: 'South-South Cooperation', narrative: `Scholars of multipolarity argue that South-South cooperation can reduce dependence on the sanctioning bloc. Do you prioritise trade and ties with other developing countries, building alternatives to Northern markets and finance? It could expand options but may mean trading with partners who have less to offer in the short term.`, choices: [{ id: 'yes', text: 'Prioritize South-South', consequence: '', effects: { sovereignty: 10, economicStrength: 6 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 2, title: 'Domestic Production', narrative: `Sanctioned goods — technology, spare parts, medicines — are hard to get. Do you invest heavily in domestic production to replace them? It could build resilience but is expensive and some things may be impossible to replicate.`, choices: [{ id: 'yes', text: 'Invest heavily', consequence: '', effects: { sovereignty: 15, economicStrength: 10, debtBurden: 10 } }, { id: 'modest', text: 'Modest investment', consequence: '', effects: { economicStrength: 5 } }] },
  { phase: 3, title: 'Capital Controls', narrative: `Capital is fleeing — sanctions and uncertainty are driving money out. Do you impose strict capital controls to stem the flow and keep resources at home? It could stabilise the economy but may deter future investment and complicate trade.`, choices: [{ id: 'yes', text: 'Impose strict controls', consequence: '', effects: { sovereignty: 12 } }, { id: 'no', text: 'No', consequence: '', effects: { economicStrength: 3 } }] },
  { phase: 3, title: 'Barter Trade', narrative: `Dollar-based trade is restricted. Do you pursue barter and non-dollar trade — swapping goods directly or using alternative currencies — to keep commerce flowing? It could bypass financial sanctions but is less efficient and may be limited in scale.`, choices: [{ id: 'yes', text: 'Pursue barter', consequence: '', effects: { sovereignty: 10, economicStrength: 5 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 3, title: 'Negotiations', narrative: `Do you offer concessions to ease sanctions — policy changes, commitments, compromises that might satisfy the sanctioning powers? It could open the door to relief but may cost sovereignty and legitimacy at home.`, choices: [{ id: 'yes', text: 'Offer concessions', consequence: '', effects: { internationalStanding: 10, sovereignty: -12 } }, { id: 'no', text: 'Hold firm', consequence: '', effects: { sovereignty: 10 } }] },
  { phase: 3, title: 'Smuggling', narrative: `Informal channels have emerged — goods flowing through third countries, grey markets, networks that bypass sanctions. Do you tolerate them to keep supplies flowing, or crack down to maintain control and avoid provoking the sanctioning powers? Tolerance may ease shortages but could undermine your position; cracking down may please critics but hurt ordinary people.`, choices: [{ id: 'tolerate', text: 'Tolerate', consequence: '', effects: { economicStrength: 8, publicSupport: 5 } }, { id: 'crack', text: 'Crack down', consequence: '', effects: { sovereignty: 5 } }] },
  { phase: 4, title: 'Mid-Term', narrative: `You have adapted — the economy has found ways to function under sanctions. Do you deepen self-reliance, investing more in domestic production and alternative partners, or seek a deal with the sanctioning powers to ease the pressure? Deepening may build lasting resilience; a deal could bring relief but at a cost.`, choices: [{ id: 'deepen', text: 'Deepen self-reliance', consequence: '', effects: { sovereignty: 15, economicStrength: 8 } }, { id: 'deal', text: 'Seek a deal', consequence: '', effects: { internationalStanding: 8, sovereignty: -8 } }] },
  { phase: 4, title: 'Technology', narrative: `Sanctioned technology — chips, software, specialised equipment — is hard to replace. Do you invest in domestic R&D to build alternatives? It could reduce dependence over time but is costly and may take years to bear fruit.`, choices: [{ id: 'yes', text: 'Invest in R&D', consequence: '', effects: { sovereignty: 12, economicStrength: 8 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 4, title: 'Regional Bloc', narrative: `Do you form a regional bloc with other sanctioned or similarly constrained states — pooling resources, coordinating trade, building alternatives to the dominant order? It could strengthen your position but may also provoke further pressure.`, choices: [{ id: 'yes', text: 'Form bloc', consequence: '', effects: { sovereignty: 12, economicStrength: 6 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 4, title: 'Humanitarian Exceptions', narrative: `Do you lobby for humanitarian exceptions — allowing food, medicine, and other essentials through the sanctions regime? It could ease suffering but may be seen as legitimising the sanctions themselves.`, choices: [{ id: 'yes', text: 'Lobby', consequence: '', effects: { publicSupport: 8, internationalStanding: 3 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 5, title: 'Year Two', narrative: `The economy has adapted — new partners, new supply chains, new ways of operating. Do you consolidate, locking in what works and managing risks, or push for more — deeper self-reliance, broader alternatives? Consolidation may stabilise; pushing further may build resilience but could overstretch.`, choices: [{ id: 'consolidate', text: 'Consolidate', consequence: '', effects: {} }, { id: 'push', text: 'Push for more', consequence: '', effects: { sovereignty: 10, economicStrength: 8 } }] },
  { phase: 5, title: 'Legacy', narrative: `What model do you leave for Persea? A sovereign economy — self-reliant, with alternative partners and payment systems? Or a path toward reintegration — positioning for a deal that could ease sanctions and restore ties?`, choices: [{ id: 'sovereign', text: 'Sovereign economy', consequence: '', effects: { sovereignty: 15 } }, { id: 'integrated', text: 'Reintegration path', consequence: '', effects: { internationalStanding: 10 } }] },
  { phase: 5, title: 'Final Push', narrative: `Do you seek one more round of negotiations with the sanctioning powers — a last attempt to ease pressure before your term ends? It could bring relief or leave you with nothing to show for the effort.`, choices: [{ id: 'yes', text: 'Seek negotiations', consequence: '', effects: { internationalStanding: 8 } }, { id: 'no', text: 'No', consequence: '', effects: { sovereignty: 8 } }] },
  { phase: 5, title: 'Final Decision', narrative: `Your last decision for Persea. The path you choose will shape whether the country survives sanctions with sovereignty intact — or finds a way back into the fold.`, choices: [{ id: 'sovereign', text: 'Sovereign path', consequence: '', effects: { sovereignty: 12, economicStrength: 6 } }, { id: 'negotiated', text: 'Negotiated path', consequence: '', effects: { internationalStanding: 10 } }, { id: 'mixed', text: 'Mixed path', consequence: '', effects: { sovereignty: 8, economicStrength: 6 } }] },
  { phase: 1, title: 'Finding New Partners', narrative: `You have pivoted to alternative partners. The question is which. Do you prioritise regional neighbours — building a bloc of similarly constrained states — or seek bilateral deals with major powers outside the sanctioning coalition? Regional blocs may be more stable; bilateral deals may bring faster relief.`, choices: [{ id: 'regional', text: 'Regional bloc', consequence: '', effects: { sovereignty: 10, economicStrength: 5 }, nextBlock: 1 }, { id: 'bilateral', text: 'Bilateral deals', consequence: '', effects: { economicStrength: 8, sovereignty: -3 }, nextBlock: 1 }] },
  { phase: 1, title: 'Building Self-Reliance', narrative: `You have chosen self-reliance. The question is where to start. Do you prioritise import substitution — producing at home what you can no longer import — or domestic R&D to build technological independence? Substitution may be faster; R&D may be more transformative.`, choices: [{ id: 'substitution', text: 'Import substitution', consequence: '', effects: { sovereignty: 12, economicStrength: 8 }, nextBlock: 1 }, { id: 'rd', text: 'Domestic R&D', consequence: '', effects: { sovereignty: 10, economicStrength: 5 }, nextBlock: 1 }] },
];

const endings: LongFormEnding[] = [
  { id: 'victory', endingType: 'victory', title: 'Sovereign Under Pressure', endingNarrative: `You built self-reliance under sanctions. Persea has found new paths and new partners.` },
  { id: 'partial', endingType: 'partial_victory', title: 'Adapted', endingNarrative: `You adapted. The economy has found ways to function. The path ahead remains difficult.` },
  { id: 'defeat', endingType: 'defeat', title: 'Isolation Deepens', endingNarrative: `Sanctions have taken their toll. The economy has contracted. The struggle continues.` },
];

const { getNode } = createLongFormTree(blocks, endings, (i) => (i === 0 ? 0 : i === 1 ? 1 : 2));
export { getNode };
