import type { DecisionBlock, LongFormEnding } from '../long-form-tree';
import { createLongFormTree } from '../long-form-tree';

/**
 * Tutorial — Republic of Calmwater (20 decisions)
 */
const blocks: DecisionBlock[] = [
  {
    phase: 1,
    title: 'Learning the Basics',
    narrative: `Welcome to the Republic of Calmwater. Some argue that markets need to be embedded in regulation — that when they run unchecked, society eventually pushes back through counter-movements. Research on inequality suggests that when returns to capital outpace growth, wealth concentrates. You will make 20 decisions. Ready?`,
    choices: [
      { id: 'balanced', text: 'Balanced approach', consequence: '', effects: { economicStrength: 5, publicSupport: 5, debtBurden: 0 } },
      { id: 'expansionary', text: 'Stimulate', consequence: '', effects: { economicStrength: 10, publicSupport: 10, debtBurden: 15 } },
      { id: 'conservative', text: 'Be conservative', consequence: '', effects: { economicStrength: -3, publicSupport: -5, debtBurden: -15 } },
    ],
  },
  { phase: 1, title: 'Tax Policy', narrative: `Taxes fund the state but also affect behaviour — higher taxes can dampen activity, lower taxes can stimulate it. Do you raise taxes to shore up the budget, lower them to spur growth, or hold them steady?`, choices: [{ id: 'raise', text: 'Raise taxes', consequence: '', effects: { debtBurden: -8, publicSupport: -5 } }, { id: 'lower', text: 'Lower taxes', consequence: '', effects: { economicStrength: 5, debtBurden: 8 } }, { id: 'hold', text: 'Hold', consequence: '', effects: {} }] },
  { phase: 1, title: 'Spending', narrative: `Government spending can boost demand and fund public goods — but it also adds to debt. Do you increase spending to stimulate the economy, cut it to balance the books, or hold steady?`, choices: [{ id: 'increase', text: 'Increase spending', consequence: '', effects: { economicStrength: 8, publicSupport: 8, debtBurden: 10 } }, { id: 'cut', text: 'Cut spending', consequence: '', effects: { debtBurden: -10, publicSupport: -8 } }, { id: 'hold', text: 'Hold', consequence: '', effects: {} }] },
  { phase: 1, title: 'Regulation', narrative: `The view that markets need to be embedded suggests that labour, land, and money should not be treated as pure commodities. Do you strengthen labour protections — wages, safety, job security — or keep current rules? Stronger protections may improve welfare but could affect competitiveness.`, choices: [{ id: 'yes', text: 'Strengthen protections', consequence: '', effects: { publicSupport: 10, economicStrength: -2 } }, { id: 'no', text: 'Keep current rules', consequence: '', effects: { economicStrength: 3 } }] },
  { phase: 2, title: 'Inequality', narrative: `Studies of wealth concentration suggest that when capital earns more than the economy grows, inequality deepens. Do you propose redistribution — wealth taxes, transfers, public services — or leave distribution to the market? Redistribution may reduce inequality but could affect incentives.`, choices: [{ id: 'yes', text: 'Propose redistribution', consequence: '', effects: { publicSupport: 12, debtBurden: -5 } }, { id: 'no', text: 'No redistribution', consequence: '', effects: { economicStrength: 5 } }] },
  { phase: 2, title: 'Infrastructure', narrative: `Infrastructure — roads, broadband, energy — supports private activity but requires upfront investment. Do you make a major investment to boost long-term growth, or keep it modest to limit debt?`, choices: [{ id: 'major', text: 'Major investment', consequence: '', effects: { economicStrength: 12, debtBurden: 10 } }, { id: 'modest', text: 'Modest investment', consequence: '', effects: { economicStrength: 6, debtBurden: 4 } }] },
  { phase: 2, title: 'Trade', narrative: `Opening trade can bring competition, efficiency, and access to markets — but it can also expose domestic firms to foreign competition. Do you open further or protect domestic industry?`, choices: [{ id: 'open', text: 'Open further', consequence: '', effects: { economicStrength: 8 } }, { id: 'protect', text: 'Protect industry', consequence: '', effects: { publicSupport: 5, economicStrength: 3 } }] },
  { phase: 2, title: 'Education', narrative: `Do you increase education spending?`, choices: [{ id: 'yes', text: 'Increase', consequence: '', effects: { economicStrength: 8, publicSupport: 8, debtBurden: 5 } }, { id: 'no', text: 'Hold', consequence: '', effects: {} }] },
  { phase: 3, title: 'Budget Balance', narrative: `The deficit is growing. Do you prioritise balance — cutting spending or raising taxes to stabilise debt — or prioritise growth, accepting higher deficits in the hope that expansion will eventually fill the gap?`, choices: [{ id: 'balance', text: 'Prioritize balance', consequence: '', effects: { debtBurden: -10, economicStrength: -5 } }, { id: 'growth', text: 'Prioritize growth', consequence: '', effects: { economicStrength: 10, debtBurden: 8 } }] },
  { phase: 3, title: 'Social Spending', narrative: `Some argue that when markets create insecurity, society pushes for protection — welfare, pensions, healthcare. Do you expand welfare to cushion people from market shocks, or hold the line? Expansion may build support but adds to spending.`, choices: [{ id: 'expand', text: 'Expand welfare', consequence: '', effects: { publicSupport: 15, debtBurden: 8 } }, { id: 'hold', text: 'Hold', consequence: '', effects: {} }] },
  { phase: 3, title: 'Interest Rates', narrative: `Inflation is rising. Central banks typically raise interest rates to cool demand. Do you support rate hikes to tame inflation, or resist — fearing they will slow growth and cost jobs? Hikes may stabilise prices but can trigger recession.`, choices: [{ id: 'yes', text: 'Support hikes', consequence: '', effects: { priceStability: 10, economicStrength: -5 } }, { id: 'no', text: 'Resist', consequence: '', effects: { economicStrength: 5, priceStability: -5 } }] },
  { phase: 3, title: 'Minimum Wage', narrative: `Do you raise the minimum wage to lift the floor for workers? It could reduce poverty but may affect employment in low-wage sectors.`, choices: [{ id: 'yes', text: 'Raise it', consequence: '', effects: { publicSupport: 12, economicStrength: 2 } }, { id: 'no', text: 'Hold', consequence: '', effects: {} }] },
  { phase: 4, title: 'Mid-Term', narrative: `Your policies have had time to work. Some are bearing fruit; others may need revision. Do you adjust — fine-tuning based on what you have learned — or stay the course?`, choices: [{ id: 'adjust', text: 'Adjust', consequence: '', effects: { economicStrength: 5, publicSupport: 5 } }, { id: 'stay', text: 'Stay the course', consequence: '', effects: {} }] },
  { phase: 4, title: 'Green Investment', narrative: `The green transition — renewable energy, efficiency, new industries — could create jobs and reduce emissions. Do you invest in it, or hold back to limit debt? Investment may pay off over time but costs money now.`, choices: [{ id: 'yes', text: 'Invest', consequence: '', effects: { economicStrength: 8, debtBurden: 8 } }, { id: 'no', text: 'No', consequence: '', effects: { debtBurden: -5 } }] },
  { phase: 4, title: 'Housing', narrative: `Social housing — publicly built or subsidised homes — can address affordability and homelessness. Do you support it? It could help many but adds to spending.`, choices: [{ id: 'yes', text: 'Support', consequence: '', effects: { publicSupport: 10, debtBurden: 5 } }, { id: 'no', text: 'No', consequence: '', effects: {} }] },
  { phase: 4, title: 'Financial Regulation', narrative: `Tighter financial regulation can reduce risk and protect consumers — but it may also constrain credit and innovation. Do you tighten it or leave it as is?`, choices: [{ id: 'yes', text: 'Tighten', consequence: '', effects: { economicStrength: 2, publicSupport: 5 } }, { id: 'no', text: 'No', consequence: '', effects: { economicStrength: 5 } }] },
  { phase: 5, title: 'Year Two', narrative: `Do you continue your approach — doubling down on what has worked — or reverse course, shifting toward a different strategy?`, choices: [{ id: 'continue', text: 'Continue', consequence: '', effects: { economicStrength: 5, publicSupport: 5 } }, { id: 'reverse', text: 'Reverse', consequence: '', effects: { debtBurden: -5 } }] },
  { phase: 5, title: 'Final Stimulus', narrative: `Growth is slowing. Do you add stimulus — more spending or tax cuts — to boost demand, or hold back to protect the budget? Stimulus may revive growth but adds to debt.`, choices: [{ id: 'yes', text: 'Add stimulus', consequence: '', effects: { economicStrength: 10, debtBurden: 10 } }, { id: 'no', text: 'No', consequence: '', effects: { debtBurden: -5 } }] },
  { phase: 5, title: 'Legacy', narrative: `What kind of economy do you leave? More redistributive — with stronger welfare and a fairer distribution of gains? Or growth-oriented — prioritising expansion over redistribution?`, choices: [{ id: 'redistributive', text: 'More redistributive', consequence: '', effects: { publicSupport: 10 } }, { id: 'growth', text: 'Growth-oriented', consequence: '', effects: { economicStrength: 10 } }] },
  { phase: 5, title: 'Final Decision', narrative: `Your last decision. You have learned the trade-offs — between growth and stability, spending and debt, openness and protection. Ready for policy mode to explore the simulation in more depth?`, choices: [{ id: 'balanced', text: 'A balanced economy', consequence: '', effects: { economicStrength: 5, publicSupport: 5, debtBurden: 0 } }, { id: 'growth', text: 'A growing economy', consequence: '', effects: { economicStrength: 10, debtBurden: 5 } }, { id: 'prudent', text: 'A prudent economy', consequence: '', effects: { debtBurden: -10, economicStrength: 2 } }] },
];

const endings: LongFormEnding[] = [
  { id: 'victory', endingType: 'victory', title: 'Well Balanced', endingNarrative: `You learned the trade-offs. Try policy mode to explore the simulation in more depth.` },
  { id: 'partial', endingType: 'partial_victory', title: 'Mixed Results', endingNarrative: `You made progress. Switch to policy mode to experiment further.` },
  { id: 'defeat', endingType: 'defeat', title: 'Learning Experience', endingNarrative: `You saw the trade-offs. Try again or switch to policy mode.` },
];

const { getNode } = createLongFormTree(blocks, endings, (i) => (i === 0 ? 0 : i === 1 ? 1 : 2));
export { getNode };
